version: '3'
services:
  dev:
    image: node:13
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/app/dev
    working_dir: /app/dev
    command: npm run dev
    depends_on:
      - ganache

  ganache:
    image: trufflesuite/ganache-cli:latest
    ports:
      - "7545:7545"
